language: android

android:
  components:
    - build-tools-26.0.0
    - android-25
    - sys-img-armeabi-v7a-android-25
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
    - chmod +x gradlew
